---
- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present

- name: Close all ports
  ufw:
    rule: deny

- name: Open required ports
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - 22
    - 80
    - 443
    - 110
    - 587
